{% set name = "pure-sasl" %}
{% set version = "0.5.0" %}
{% set hashtype = "sha256" %}
{% set hash =  '198fc63d8670e62696a0ebc17baebc278afa67264eb09e164813121c67b002e6' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hashtype }}: {{ hash }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - puresasl

about:
  home: https://github.com/thobbs/pure-sasl
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/thobbs/pure-sasl
  doc_url: https://github.com/thobbs/pure-sasl
  summary: A pure python SASL client

extra:
  recipe-maintainers:
    - mariusvniekerk
    - ericdill
