{% set name = "pure-sasl" %}
{% set version = "0.5.1" %}
{% set sha256 =  '25ba5dbb6eb25850a5e5509a8266f3bc506cf05eccacdb07613fbe82dc8a10f8' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-dependencies --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - puresasl

about:
  home: https://github.com/thobbs/pure-sasl
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/thobbs/pure-sasl
  doc_url: https://github.com/thobbs/pure-sasl
  summary: Pure Python client SASL implementation
  description: |
    This package provides a reasonably high-level SASL client written in pure
    Python. By default, support for PLAIN, ANONYMOUS, CRAM-MD5, DIGEST-MD5, and
    GSSAPI is provided.

extra:
  recipe-maintainers:
    - mariusvniekerk
    - ericdill
