travis:
  secure:
    BINSTAR_TOKEN: CASMJ2m879RbBuc3DuntJVxPef7Mn8RKs19qvsKFu3jJdovEt1ESUKaxVwGA4bIO0K/6VwDAJPcoTAkcwE2QzCiKk3KsUwDAVAfyOcwwaY6EpmfqkToV+clElPA71XZHNvxyPARKOpbVHDqU7QJTK31kb3LhxLmKaQcYeofbMND+Zf26qASv7ONCGJD7+AAXxyuu+St8k04IFAGBl0Zw0RjCBMW9HlDPbqPEzagfX2fRcv7UYuqQLfMQsQ2O+l+SeE6uUZQHKwVjjn/+vAUm8DNIKoLTxsw5EVFMMK3LJEBjbxL8SOLqgvYRCG9dIeFQrxQyErWD03htadcORRXT6MFDx4TBbIPaneQwCTTWlgYzomyRdiYYMIOQP/FChyel07zL91RIS1PxqJfBzbbMz5nfz8d3nDR0Owm5Db6Hh3ZGkslPVFU2nRYO5vzbKe0jaOLjUgLdUbKMe3ZkdACsw347UvID/+PyWfuXT1F7Fhu1ENXySShg+tRBKvZsZ4bcbx91ZklF71zWC1fNCBlCDnVq0BkmxKk6KiJFv50e45ozHvekRif3N3iWUG2vGkimclkK5bIHQ66Op8OnRQMEI+AgZOKT0QuTSUVmFE45+DN861kyzIvP9JFVobq2A/nVNN290J0G0he6XIEZYNuqP58Yh9fLKyl/l/FenRGwrnI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
